### ISSUE TITLE
No list of ZFS Pools

### ISSUE THREAD

**Issue by bjornbouetsmith** [jonmatifa/zfsmanager#14]
Hi just installed latest via git pull.

Menu appears in my list after I do the work around with user assignment of allowed modules.

But when opening ZFS Manager i just get an empty list.

I have configured the module via "Module Config".

When I create a new pool via "Create new pool" - the pool successfully appears in linux when I run zpool status or zpool list.

So the integration to linux works in that direction - it just seems like something goes wrong when actually reading the current ZFS configuration.

Looking in the HTML code generated its empty as well.

Anything I can do to help diagnose this?

**Comment by bjornbouetsmith** [comment]
Looked in #12  and adding the lines:
list_zpool=size,alloc,free,frag,cap,dedup,health
list_zfs=used,avail,refer,mountpoint

to the /etc/webmin/zfsmanager/config made the pools appear.

So perhaps you just need to add this to the standard configuration file?

**Comment by jonmatifa** [comment]
Did you have it installed previously? Those lines are in the config file, but will only update the template one located under the webmin root (such as /usr/share/webmin/zfsmanager) rather than the current running config out at /etc/webmin/zfsmanager/

I suppose I could add a function to validate the config and add in missing parameters as needed...

**Comment by jonmatifa** [comment]
Referring to issue #12

**Comment by bjornbouetsmith** [comment]
No this was a fresh installation that I did with a git clone as described. 
Although I did not copy any config file anywhere. So it seems like the default values for the config is missing some settings.
